packages:
  - "apps/backend"
  - "apps/dashboard"
  - "apps/admin"
  - "apps/marketing"
  - "apps/bespoke/*/website"
  - "apps/mobile"
  - "packages/shared"
  - "packages/api-client"
  - "packages/ui"
  - "packages/*"
