// Each segment maps to a translation key under the 'breadcrumbs' namespace.
export const BREADCRUMB_TRAILS: Record<string, Array<{ key: string; href?: string }>> = {
  '/': [{ key: 'home' }],
  '/organizations': [{ key: 'home', href: '/' }, { key: 'organizations' }],
  '/organizations/new': [
    { key: 'home', href: '/' },
    { key: 'organizations', href: '/organizations' },
    { key: 'createOrg' },
  ],
  '/organizations/:id': [
    { key: 'home', href: '/' },
    { key: 'organizations', href: '/organizations' },
    { key: 'detail' },
  ],
  '/plans': [{ key: 'home', href: '/' }, { key: 'plans' }],
  '/plans/:id/edit': [
    { key: 'home', href: '/' },
    { key: 'plans', href: '/plans' },
    { key: 'edit' },
  ],
  '/plans/new': [{ key: 'home', href: '/' }, { key: 'plans', href: '/plans' }, { key: 'new' }],
  '/plans/compare': [{ key: 'home', href: '/' }, { key: 'plans', href: '/plans' }, { key: 'compare' }],
  '/verticals': [{ key: 'home', href: '/' }, { key: 'verticals' }],
  '/billing': [{ key: 'home', href: '/' }, { key: 'billing' }],
  '/billing/:orgId': [
    { key: 'home', href: '/' },
    { key: 'billing', href: '/billing' },
    { key: 'organization' },
  ],
  '/billing/invoices': [
    { key: 'home', href: '/' },
    { key: 'billing', href: '/billing' },
    { key: 'invoices' },
  ],
  '/billing/metrics': [
    { key: 'home', href: '/' },
    { key: 'billing', href: '/billing' },
    { key: 'metrics' },
  ],
  '/billing/zoho': [
    { key: 'home', href: '/' },
    { key: 'billing', href: '/billing' },
    { key: 'zoho' },
  ],
  '/audit-log': [{ key: 'home', href: '/' }, { key: 'auditLog' }],
  '/impersonation-sessions': [{ key: 'home', href: '/' }, { key: 'impersonation' }],
  '/users': [{ key: 'home', href: '/' }, { key: 'users' }],
  '/notifications': [{ key: 'home', href: '/' }, { key: 'notifications' }],
  '/metrics': [{ key: 'home', href: '/' }, { key: 'metrics' }],
  '/settings': [{ key: 'home', href: '/' }, { key: 'settings' }],
  '/settings/email': [
    { key: 'home', href: '/' },
    { key: 'settings', href: '/settings' },
    { key: 'email' },
  ],
  '/settings/email/templates': [
    { key: 'home', href: '/' },
    { key: 'settings', href: '/settings' },
    { key: 'email', href: '/settings/email' },
    { key: 'templates' },
  ],
  '/settings/email/templates/:slug': [
    { key: 'home', href: '/' },
    { key: 'settings', href: '/settings' },
    { key: 'email', href: '/settings/email' },
    { key: 'templates', href: '/settings/email/templates' },
    { key: 'edit' },
  ],
  '/settings/email/logs': [
    { key: 'home', href: '/' },
    { key: 'settings', href: '/settings' },
    { key: 'email', href: '/settings/email' },
    { key: 'logs' },
  ],
  '/settings/notifications': [
    { key: 'home', href: '/' },
    { key: 'settings', href: '/settings' },
    { key: 'notifications' },
  ],
  '/settings/billing': [
    { key: 'home', href: '/' },
    { key: 'settings', href: '/settings' },
    { key: 'billing' },
  ],
  '/settings/health': [
    { key: 'home', href: '/' },
    { key: 'settings', href: '/settings' },
    { key: 'health' },
  ],
  '/settings/security': [
    { key: 'home', href: '/' },
    { key: 'settings', href: '/settings' },
    { key: 'security' },
  ],
};
